export const ACCESS_REQUEST_FAILED = "ACCESS_REQUEST_FAILED";
export const ACCESS_REQUEST_PENDING = "ACCESS_REQUEST_PENDING";
export const ACCESS_REQUEST_SUCCESS = "ACCESS_REQUEST_SUCCESS";

export const CLICK_ADD_BOOK_TO_BOOKLIST_FAILED = "CLICK_ADD_BOOK_TO_BOOKLIST_FAILED";
export const CLICK_ADD_BOOK_TO_BOOKLIST_PENDING = "CLICK_ADD_BOOK_TO_BOOKLIST_PENDING";
export const CLICK_ADD_BOOK_TO_BOOKLIST_SUCCESS = "CLICK_ADD_BOOK_TO_BOOKLIST_SUCCESS";

export const CLICK_BOOK = "CLICK_BOOK";
export const CLICK_LIST = "CLICK_LIST";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORDCHECK = "CHANGE_PASSWORDCHECK";

export const CLICK_SHORTEN_RECOMMENDATIONS_BY_FEELING = "CLICK_SHORTEN_RECOMMENDATIONS_BY_FEELING";

export const CHANGE_USER_ID = "CHANGE_USER_ID";

export const EMAIL_REQUEST_FAILED = "EMAIL_REQUEST_FAILED";
export const EMAIL_REQUEST_PENDING = "EMAIL_REQUEST_PENDING";
export const EMAIL_REQUEST_SUCCESS = "EMAIL_REQUEST_SUCCESS";

export const LIST_BOOKS_REQUEST_FAILED = "LIST_BOOKS_REQUEST_FAILED";
export const LIST_BOOKS_REQUEST_PENDING = "LIST_BOOKS_REQUEST_PENDING";
export const LIST_BOOKS_REQUEST_SUCCESS = "LIST_BOOKS_REQUEST_SUCCESS";

export const LOGIN_REQUEST_FAILED = "LOGIN_REQUEST_FAILED";
export const LOGIN_REQUEST_PENDING = "LOGIN_REQUEST_PENDING";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";

export const SIGN_UP_REQUEST_FAILED = "SIGN_UP_REQUEST_FAILED";
export const SIGN_UP_REQUEST_PENDING = "SIGN_UP_REQUEST_PENDING";
export const SIGN_UP_REQUEST_SUCCESS = "SIGN_UP_REQUEST_SUCCESS";

export const RECOMMENDATIONS_BY_FEELING_REQUEST_PENDING = "RECOMMENDATIONS_BY_FEELING_REQUEST_PENDING";
export const RECOMMENDATIONS_BY_FEELING_REQUEST_SUCCESS = "RECOMMENDATIONS_BY_FEELING_REQUEST_SUCCESS";
export const RECOMMENDATIONS_BY_FEELING_REQUEST_FAILED = "RECOMMENDATIONS_BY_FEELING_REQUEST_FAILED";

export const RECOMMENDATIONS_BY_ID_REQUEST_PENDING = "RECOMMENDATIONS_BY_ID_REQUEST_PENDING";
export const RECOMMENDATIONS_BY_ID_REQUEST_SUCCESS = "RECOMMENDATIONS_BY_ID_REQUEST_SUCCESS";
export const RECOMMENDATIONS_BY_ID_REQUEST_FAILED = "RECOMMENDATIONS_BY_ID_REQUEST_FAILED";

export const RECOMMENDATIONS_RANDOM_REQUEST_PENDING = "RECOMMENDATIONS_RANDOM_REQUEST_PENDING";
export const RECOMMENDATIONS_RANDOM_REQUEST_SUCCESS = "RECOMMENDATIONS_RANDOM_REQUEST_SUCCESS";
export const RECOMMENDATIONS_RANDOM_REQUEST_FAILED = "RECOMMENDATIONS_RANDOM_REQUEST_FAILED";

export const TWEET_REQUEST_FAILED = "TWEET_REQUEST_FAILED";
export const TWEET_REQUEST_PENDING = "TWEET_REQUEST_PENDING";
export const TWEET_REQUEST_SUCCESS = "TWEET_REQUEST_SUCCESS";
